apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS petclinic;
    DEFAULT CHARACTER SET utf8;
    DEFAULT COLLATE utf8_general_ci;
    GRANT ALL PRIVILEGES ON petclinic.* TO 'petclinic'@'%' IDENTIFIED BY 'petclinic';
    
    CREATE TABLE IF NOT EXISTS vets (
     id INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
     first_name VARCHAR(30),
     last_name VARCHAR(30),
     INDEX(last_name)
    ) engine=InnoDB;

    CREATE TABLE IF NOT EXISTS specialties (
     id INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
     name VARCHAR(80),
     INDEX(name)
    ) engine=InnoDB;

    CREATE TABLE IF NOT EXISTS vet_specialties (
     vet_id INT(4) UNSIGNED NOT NULL,
     specialty_id INT(4) UNSIGNED NOT NULL,
     FOREIGN KEY (vet_id) REFERENCES vets(id),
     FOREIGN KEY (specialty_id) REFERENCES specialties(id),
     UNIQUE (vet_id,specialty_id)
    ) engine=InnoDB;
   
    CREATE TABLE IF NOT EXISTS types (
     id INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
     name VARCHAR(80),
     INDEX(name)
    ) engine=InnoDB;

    CREATE TABLE IF NOT EXISTS owners (
     id INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
     first_name VARCHAR(30),
     ast_name VARCHAR(30),
     address VARCHAR(255),
     city VARCHAR(80),
     telephone VARCHAR(20),
     INDEX(last_name)
    ) engine=InnoDB;

    CREATE TABLE IF NOT EXISTS pets (
     id INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
     name VARCHAR(30),
     birth_date DATE,
     type_id INT(4) UNSIGNED NOT NULL,
     owner_id INT(4) UNSIGNED,
     INDEX(name),
     FOREIGN KEY (owner_id) REFERENCES owners(id),
     FOREIGN KEY (type_id) REFERENCES types(id)
    ) engine=InnoDB;

    CREATE TABLE IF NOT EXISTS visits (
     id INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
     pet_id INT(4) UNSIGNED,
     visit_date DATE,
     description VARCHAR(255),
     FOREIGN KEY (pet_id) REFERENCES pets(id)
    ) engine=InnoDB;
   
    INSERT IGNORE INTO vets VALUES (1, 'James', 'Carter');
    INSERT IGNORE INTO specialties VALUES (1, 'radiology');
    INSERT IGNORE INTO specialties VALUES (2, 'surgery');
    INSERT IGNORE INTO specialties VALUES (3, 'dentistry');
    INSERT IGNORE INTO types VALUES (1, 'cat');
    INSERT IGNORE INTO types VALUES (2, 'dog');
    INSERT IGNORE INTO types VALUES (3, 'lizard');
    INSERT IGNORE INTO types VALUES (4, 'snake');
    INSERT IGNORE INTO types VALUES (5, 'bird');
    INSERT IGNORE INTO types VALUES (6, 'hamster');
    INSERT IGNORE INTO owners VALUES (1, 'George', 'Franklin', '110 W. Liberty St.', 'Madison', '6085551023');
    INSERT IGNORE INTO pets VALUES (1, 'Leo', '2000-09-07', 1, 1);
    INSERT IGNORE INTO visits VALUES (1, 7, '2010-03-04', 'rabies shot');
